name: EasyStreet
options:
  bundleIdPrefix: com.easystreet
  deploymentTarget:
    iOS: "14.0"
  createIntermediateGroups: true

targets:
  EasyStreet:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.md"
          - "*.csv"
          - "EasyStreet.xcodeproj"
          - "project.yml"
    resources:
      - path: LaunchScreen.storyboard
      - path: sweeping_data_sf.json
      - path: easystreet.db
        optional: true
      - path: Assets.xcassets
      - path: Info.plist
        buildPhase: none
    dependencies:
      - sdk: libsqlite3.tbd
      - sdk: Network.framework
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.easystreet.app
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  EasyStreetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../EasyStreetTests
    dependencies:
      - target: EasyStreet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.easystreet.app.tests
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
